"""Tests for the commit classifier — heuristics, overrides, AI detection."""

from __future__ import annotations

from datetime import datetime, timezone

from repocheck.classifier import (
    CommitType,
    _apply_overrides,
    _estimate_ai_assisted,
    _heuristic_classify,
    _size_from_lines,
)
from repocheck.extractor import CommitData, FileChange


def _make_commit(
    summary: str = "some commit",
    insertions: int = 10,
    deletions: int = 5,
    files: list[FileChange] | None = None,
    author_name: str = "dev",
    author_email: str = "dev@test.com",
    message: str | None = None,
) -> CommitData:
    return CommitData(
        sha="a" * 40,
        short_sha="a" * 8,
        author_name=author_name,
        author_email=author_email,
        authored_date=datetime(2025, 1, 1, tzinfo=timezone.utc),
        committer_name=author_name,
        committed_date=datetime(2025, 1, 1, tzinfo=timezone.utc),
        message=message or summary,
        summary=summary,
        files=files or [],
        total_insertions=insertions,
        total_deletions=deletions,
        total_files_changed=len(files) if files else 1,
        is_merge=False,
    )


class TestSizeFromLines:
    def test_trivial(self):
        assert _size_from_lines(5) == "trivial"

    def test_small(self):
        assert _size_from_lines(30) == "small"

    def test_medium(self):
        assert _size_from_lines(100) == "medium"

    def test_large(self):
        assert _size_from_lines(400) == "large"

    def test_massive(self):
        assert _size_from_lines(1000) == "massive"


class TestHeuristicClassify:
    def test_deploy_is_chore(self):
        c = _make_commit("Deploy API Server versions: dev=dev-abc, prod=prod-abc")
        assert _heuristic_classify(c) == CommitType.CHORE

    def test_fix_is_bugfix(self):
        c = _make_commit("fix: resolve null pointer in auth")
        assert _heuristic_classify(c) == CommitType.BUGFIX

    def test_feat_is_feature(self):
        c = _make_commit("feat: add user dashboard")
        assert _heuristic_classify(c) == CommitType.FEATURE

    def test_revert(self):
        c = _make_commit('Revert "bad commit"')
        assert _heuristic_classify(c) == CommitType.REVERT

    def test_refactor(self):
        c = _make_commit("refactor auth module")
        assert _heuristic_classify(c) == CommitType.REFACTOR

    def test_unknown(self):
        c = _make_commit("WIP stuff")
        assert _heuristic_classify(c) == CommitType.UNKNOWN

    def test_version_bump_is_chore(self):
        c = _make_commit("versions: dev=abc prod=abc")
        assert _heuristic_classify(c) == CommitType.CHORE


class TestOverrides:
    def test_deploy_overrides_feature(self):
        c = _make_commit("Deploy API Server versions: dev=dev-xxx, prod=prod-xxx")
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.CHORE

    def test_version_hash_is_chore(self):
        c = _make_commit("Api v dev abc123 prod abc123")
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.CHORE

    def test_revert_override(self):
        c = _make_commit('Revert "some feature (#123)"')
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.REVERT

    def test_fix_overrides_misclassified_feature(self):
        c = _make_commit("Fix alert cursor starvation")
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.BUGFIX

    def test_real_feature_not_overridden(self):
        c = _make_commit("Standalone alerts frontend and alerts redesign (#4090)")
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.FEATURE

    def test_version_only_files(self):
        files = [FileChange("version.txt", 1, 1)]
        c = _make_commit("bump", files=files)
        assert _apply_overrides(c, CommitType.FEATURE) == CommitType.CHORE


class TestAIAssisted:
    def test_bot_author(self):
        c = _make_commit(author_name="cursor[bot]", author_email="bot@github.com")
        assert _estimate_ai_assisted(c) is True

    def test_ai_message_mention(self):
        c = _make_commit(message="fix auth\n\nGenerated by Cursor")
        assert _estimate_ai_assisted(c) is True

    def test_large_bulk_insert(self):
        c = _make_commit(
            insertions=800,
            deletions=10,
            files=[FileChange(f"f{i}.ts", 80, 1) for i in range(12)],
        )
        assert _estimate_ai_assisted(c) is True

    def test_normal_commit_not_flagged(self):
        c = _make_commit(insertions=50, deletions=20)
        assert _estimate_ai_assisted(c) is False
