"""Classify commits using OpenAI.

Runs LLM batches in parallel with ThreadPoolExecutor.
Post-processes with deterministic override rules to catch what the LLM misses.
Falls back to heuristic classification when no API key is available.
"""

from __future__ import annotations

import json
import logging
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from enum import Enum

from openai import OpenAI

from .extractor import CommitData

log = logging.getLogger(__name__)

BATCH_SIZE = 50
MAX_WORKERS = 10


class CommitType(str, Enum):
    FEATURE = "feature"
    BUGFIX = "bugfix"
    REFACTOR = "refactor"
    DOCS = "docs"
    TEST = "test"
    CHORE = "chore"
    STYLE = "style"
    PERF = "perf"
    REVERT = "revert"
    UNKNOWN = "unknown"


class CommitSize(str, Enum):
    TRIVIAL = "trivial"
    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"
    MASSIVE = "massive"


@dataclass
class ClassifiedCommit:
    commit: CommitData
    commit_type: CommitType
    size: CommitSize
    complexity_score: float
    impact_summary: str
    is_ai_assisted: bool
    confidence: float

    @property
    def is_feature_work(self) -> bool:
        return self.commit_type in (CommitType.FEATURE, CommitType.PERF)

    @property
    def is_fix(self) -> bool:
        return self.commit_type == CommitType.BUGFIX

    @property
    def is_maintenance(self) -> bool:
        return self.commit_type in (
            CommitType.REFACTOR,
            CommitType.DOCS,
            CommitType.TEST,
            CommitType.CHORE,
            CommitType.STYLE,
        )


def _size_from_lines(total: int) -> CommitSize:
    if total < 10:
        return CommitSize.TRIVIAL
    if total < 50:
        return CommitSize.SMALL
    if total < 200:
        return CommitSize.MEDIUM
    if total < 500:
        return CommitSize.LARGE
    return CommitSize.MASSIVE


# ---------------------------------------------------------------------------
# Deterministic override rules — these ALWAYS win over LLM classification.
# Order matters: first match wins.
# ---------------------------------------------------------------------------

_OVERRIDE_CHORE = re.compile(
    r"^deploy\b|^version\b|versions:|"
    r"\bdev=dev-|prod=prod-|"
    r"^bump\b|^release\b|"
    r"^\w+ v dev |^\w+ v prod |"
    r"^merge branch|^merge pull request",
    re.I,
)

_OVERRIDE_REVERT = re.compile(r"^revert\b", re.I)

_OVERRIDE_FIX = re.compile(
    r"^fix\b|^hotfix\b|^bugfix\b",
    re.I,
)


def _apply_overrides(commit: CommitData, llm_type: CommitType) -> CommitType:
    """Hard rules that catch what the LLM gets wrong."""
    msg = commit.summary.strip()

    if _OVERRIDE_CHORE.search(msg):
        return CommitType.CHORE
    if _OVERRIDE_REVERT.search(msg):
        return CommitType.REVERT
    if llm_type == CommitType.FEATURE and _OVERRIDE_FIX.search(msg):
        return CommitType.BUGFIX

    only_version_files = (
        all(
            "version" in f.path.lower() or f.path.endswith(".lock")
            for f in commit.files
        )
        if commit.files
        else False
    )
    if only_version_files and commit.total_files_changed <= 3:
        return CommitType.CHORE

    return llm_type


# ---------------------------------------------------------------------------
# AI-assisted detection heuristic
#
# In 2025-2026 almost everyone uses AI. Trying to detect it from diff style
# is unreliable. Instead we use structural signals that correlate with
# AI-heavy workflows:
#   - Very large commits with high file count (AI generates bulk code)
#   - Author is a bot
#   - Commit message has typical AI patterns
#   - High ratio of new code vs modifications (AI writes from scratch)
# ---------------------------------------------------------------------------

_BOT_PATTERNS = re.compile(
    r"\[bot\]|bot$|copilot|dependabot|renovate|greenkeeper", re.I
)
_AI_MSG_PATTERNS = re.compile(
    r"generated by|auto-generated|co-authored-by.*copilot|"
    r"cursor|copilot|aider|codeium",
    re.I,
)


def _estimate_ai_assisted(commit: CommitData) -> bool:
    if _BOT_PATTERNS.search(commit.author_name) or _BOT_PATTERNS.search(
        commit.author_email
    ):
        return True

    if _AI_MSG_PATTERNS.search(commit.message):
        return True

    total_lines = commit.total_insertions + commit.total_deletions
    if total_lines > 500 and commit.total_files_changed > 10:
        insert_ratio = commit.total_insertions / max(total_lines, 1)
        if insert_ratio > 0.85:
            return True

    if total_lines > 300 and commit.total_insertions > 250:
        insert_ratio = commit.total_insertions / max(total_lines, 1)
        if insert_ratio > 0.9 and commit.total_files_changed >= 5:
            return True

    return False


# ---------------------------------------------------------------------------
# Heuristic fallback (no API key)
# ---------------------------------------------------------------------------

_HEURISTIC_PATTERNS: list[tuple[re.Pattern, CommitType]] = [
    (
        re.compile(r"^deploy\b|versions:|dev=dev-|prod=prod-|^\w+ v dev ", re.I),
        CommitType.CHORE,
    ),
    (
        re.compile(
            r"\bfix(es|ed)?\b|\bbug\b|\bhotfix\b|\bpatch\b|\bresolve[sd]?\b", re.I
        ),
        CommitType.BUGFIX,
    ),
    (re.compile(r"\brevert\b", re.I), CommitType.REVERT),
    (re.compile(r"\bdocs?\b|\breadme\b|\bchangelog\b|\btypo\b", re.I), CommitType.DOCS),
    (re.compile(r"\btest[s]?\b|\bspec\b|\bcoverage\b", re.I), CommitType.TEST),
    (
        re.compile(r"\brefactor\b|\bclean\s?up\b|\brestructure\b", re.I),
        CommitType.REFACTOR,
    ),
    (
        re.compile(r"\bstyle\b|\blint\b|\bformat\b|\bprettier\b|\beslint\b", re.I),
        CommitType.STYLE,
    ),
    (re.compile(r"\bperf\b|\boptimize\b|\bspeed\b|\bcache\b", re.I), CommitType.PERF),
    (
        re.compile(
            r"\bchore\b|\bbump\b|\bdeps?\b|\bci\b|\bcd\b|\bbuild\b|\brelease\b", re.I
        ),
        CommitType.CHORE,
    ),
    (
        re.compile(
            r"\bfeat\b|\badd\b|\bimplement\b|\bintroduce\b|\bnew\b|\bsupport\b", re.I
        ),
        CommitType.FEATURE,
    ),
]


def _heuristic_classify(c: CommitData) -> CommitType:
    text = c.summary
    for pattern, ctype in _HEURISTIC_PATTERNS:
        if pattern.search(text):
            return ctype
    return CommitType.UNKNOWN


def _heuristic_batch(commits: list[CommitData]) -> list[ClassifiedCommit]:
    results = []
    for c in commits:
        ctype = _heuristic_classify(c)
        ctype = _apply_overrides(c, ctype)
        total = c.total_insertions + c.total_deletions
        results.append(
            ClassifiedCommit(
                commit=c,
                commit_type=ctype,
                size=_size_from_lines(total),
                complexity_score=min(1.0, total / 500),
                impact_summary=c.summary,
                is_ai_assisted=_estimate_ai_assisted(c),
                confidence=0.5,
            )
        )
    return results


# ---------------------------------------------------------------------------
# LLM classification
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """You are a senior engineering analyst classifying git commits.

For each commit, return a JSON object per commit in this format:
[
  {
    "sha": "<short sha>",
    "type": "feature|bugfix|refactor|docs|test|chore|style|perf|revert|unknown",
    "complexity": <float 0-1>,
    "impact": "<one sentence: what shipped or changed>"
  }
]

CRITICAL classification rules — read carefully:

"chore" (NOT feature):
  - Deployment commits ("Deploy API Server versions: ...", version bumps)
  - CI/CD changes, build config, dependency updates
  - Merge commits, branch syncs
  - Commits that only change version files or lock files
  - Commits whose message is just version hashes or deployment tags

"feature": ONLY genuinely new user-facing functionality or capability.
  Not every "Add X" is a feature — "Add CI pipeline" is chore, "Add user dashboard" is feature.

"bugfix": fixing broken behavior, not "fixing" typos (that's style/docs).

"refactor": restructuring without behavior change.
"perf": measurable performance improvement.

complexity: 0 = trivial change, 1 = complex architectural change.
  Version bumps and deploys = 0.

Use the commit message, file paths, and change stats to classify.
Be skeptical — many commits that say "add" or "implement" are actually small fixes or config."""


def _llm_classify_batch(
    client: OpenAI,
    commits: list[CommitData],
    model: str,
    batch_idx: int,
    total_batches: int,
) -> tuple[int, list[dict]]:
    log.info(
        "  LLM batch %d/%d (%d commits)", batch_idx + 1, total_batches, len(commits)
    )

    user_content = "\n\n---\n\n".join(
        f"SHA: {c.short_sha}\nAuthor: {c.author_name}\nDate: {c.authored_date.isoformat()}\n"
        f"Message: {c.message[:300]}\n"
        f"Files ({c.total_files_changed}): {c.file_paths_str}\n"
        f"Stats: +{c.total_insertions} -{c.total_deletions}"
        for c in commits
    )

    try:
        resp = client.chat.completions.create(
            model=model,
            temperature=0.1,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            response_format={"type": "json_object"},
        )

        raw = resp.choices[0].message.content or "[]"
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            parsed = (
                parsed.get("commits")
                or parsed.get("results")
                or list(parsed.values())[0]
            )
        return batch_idx, (parsed if isinstance(parsed, list) else [])
    except Exception as e:
        log.warning(
            "LLM batch %d failed: %s — falling back to heuristic", batch_idx + 1, e
        )
        return batch_idx, []


def _anthropic_classify_batch(
    api_key: str,
    commits: list[CommitData],
    model: str,
    batch_idx: int,
    total_batches: int,
) -> tuple[int, list[dict]]:
    """Classify using Anthropic's API."""
    import anthropic

    log.info(
        "  Anthropic batch %d/%d (%d commits)",
        batch_idx + 1,
        total_batches,
        len(commits),
    )

    user_content = "\n\n---\n\n".join(
        f"SHA: {c.short_sha}\nAuthor: {c.author_name}\nDate: {c.authored_date.isoformat()}\n"
        f"Message: {c.message[:300]}\n"
        f"Files ({c.total_files_changed}): {c.file_paths_str}\n"
        f"Stats: +{c.total_insertions} -{c.total_deletions}"
        for c in commits
    )

    try:
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=model,
            max_tokens=4096,
            system=_SYSTEM_PROMPT + "\n\nReturn ONLY valid JSON, no markdown fences.",
            messages=[{"role": "user", "content": user_content}],
        )
        raw = resp.content[0].text
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            parsed = (
                parsed.get("commits")
                or parsed.get("results")
                or list(parsed.values())[0]
            )
        return batch_idx, (parsed if isinstance(parsed, list) else [])
    except Exception as e:
        log.warning("Anthropic batch %d failed: %s", batch_idx + 1, e)
        return batch_idx, []


def classify_commits(
    commits: list[CommitData],
    openai_api_key: str | None = None,
    model: str = "gpt-4o-mini",
    provider: str = "openai",
    anthropic_api_key: str | None = None,
    progress_callback=None,
) -> list[ClassifiedCommit]:
    """Classify all commits. Uses LLM in parallel if key provided, else heuristic."""

    # Resolve provider and key
    if provider == "anthropic" and anthropic_api_key:
        api_key = anthropic_api_key
    else:
        api_key = openai_api_key or os.environ.get("OPENAI_API_KEY")
        provider = "openai"

    if not api_key:
        log.info("No API key — using heuristic classification")
        return _heuristic_batch(commits)

    log.info(
        "Classifying %d commits with %s/%s (%d workers)",
        len(commits),
        provider,
        model,
        MAX_WORKERS,
    )

    classify_fn = (
        _llm_classify_batch if provider == "openai" else _anthropic_classify_batch
    )
    client_or_key = OpenAI(api_key=api_key) if provider == "openai" else api_key

    batches: list[tuple[int, list[CommitData]]] = []
    for i in range(0, len(commits), BATCH_SIZE):
        batches.append((len(batches), commits[i : i + BATCH_SIZE]))

    total_batches = len(batches)
    batch_results: dict[int, list[dict]] = {}

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {
            pool.submit(
                classify_fn, client_or_key, batch, model, idx, total_batches
            ): idx
            for idx, batch in batches
        }

        done_count = 0
        for future in as_completed(futures):
            idx, llm_result = future.result()
            batch_results[idx] = llm_result
            done_count += 1
            if progress_callback:
                progress_callback(done_count, total_batches)

    results: list[ClassifiedCommit] = []
    for idx, batch in batches:
        llm_results = batch_results.get(idx, [])
        sha_map = {r.get("sha", ""): r for r in llm_results}

        for c in batch:
            llm = sha_map.get(c.short_sha, {})
            total = c.total_insertions + c.total_deletions

            try:
                raw_type = CommitType(llm.get("type", "unknown"))
            except ValueError:
                raw_type = CommitType.UNKNOWN

            final_type = _apply_overrides(c, raw_type)

            results.append(
                ClassifiedCommit(
                    commit=c,
                    commit_type=final_type,
                    size=_size_from_lines(total),
                    complexity_score=float(
                        llm.get("complexity", min(1.0, total / 500))
                    ),
                    impact_summary=llm.get("impact", c.summary),
                    is_ai_assisted=_estimate_ai_assisted(c),
                    confidence=float(llm.get("confidence", 0.7)),
                )
            )

    overridden = sum(
        1
        for r in results
        if _apply_overrides(r.commit, CommitType.FEATURE) != CommitType.FEATURE
    )
    log.info(
        "Classification complete: %d commits (%d overridden by rules)",
        len(results),
        overridden,
    )
    return results
